### ISSUE TITLE
Bug - Ticket overviews leads to a "404 Not found" page when click on a ticket

### ISSUE THREAD

**Issue by maureliosilverio** [znuny/znuny7-preview#1]
### Environment

- OS:  Ubuntu 20.04
- Browser:  Firefox 109.0
- Znuny version: Znuny 7 Preview

### Expected behaviour

If you click on Tickets > Status view and then on any ticket in the list, you should go to the ticket details page. You should have the same result with Queue, Service and Escalation views.

### Actual behaviour

You are redirected to a 404 not found page.

### How to reproduce

1. Go to the Agent interface
2. Click on Tickets and select any Ticket overview (e.g Status View)
3. Click on any ticket
4. See the 404 page

### Additional information

The screenshot below shows that the link is missing /otrs/index.pl?

### Screenshots

![image](https://user-images.githubusercontent.com/1065844/216849721-30d2773f-9404-4d9b-846d-1dc543568b69.png)

**Comment by dignin** [comment]
Hi, @maureliosilverio . Great to see your interest in the new software. Yes, this seems to be an issue. We will release a new version this week. Please access the tickets via the dashboard where possible meanwhile.

**Comment by maureliosilverio** [comment]
OK @dignin , the dashboard links are working. Thanks!!

By the way, great job so far :)

**Comment by dignin** [comment]
@maureliosilverio , the new release is available. https://github.com/znuny/znuny7-preview/releases/download/7.0.0.2/znuny-7.0.0.2.tar.gz

**Comment by maureliosilverio** [comment]
> @maureliosilverio , the new release is available. https://github.com/znuny/znuny7-preview/releases/download/7.0.0.2/znuny-7.0.0.2.tar.gz

Perfect. I'll test ASAP. Thanks!!!
