### ISSUE TITLE
Bug - Unable to create a new ticket as a customer user

### ISSUE THREAD

**Issue by maureliosilverio** [znuny/znuny7-preview#2]
### Environment

- OS:  Ubuntu 20.04
- Browser:  Firefox 109.0
- Znuny version: 7.0.0.2

### Expected behaviour

The customer logs in to the system and opens a new ticket

### Actual behaviour

After clicking Send button, the system shows an error message

### How to reproduce

1. Login as customer user into <znuny_url>/otrs/customer.pl
2. Click on 'Create Ticket'
3. Fill out the form and click on Send button
4. See the error

### Additional information

![image](https://user-images.githubusercontent.com/1065844/218265583-eb2e04dd-af68-4411-a035-5164946a35b4.png)

**Comment by dignin** [comment]
Thanks for your report. We are fixing the issue.

**Comment by dignin** [comment]
Is included in the next preview release.
